# Generated by Django 5.1.5 on 2026-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_investmenttier_capital_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttier',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business'), ('COMPANY', 'Company'), ('TRIPLE_STAKE', 'Triple Stake Plan')], max_length=20, unique=True),
        ),
    ]
